### ISSUE TITLE
Nintendo switch players cannot be found

### ISSUE THREAD

**Issue by meeow** [s32x/ovrstat#55] opened 2020-12-21 09:22 UTC
Samples:

**Private profile user**
Exists on blizzard end - https://playoverwatch.com/en-us/career/nintendo-switch/LSB-82d57a445ee3315fe83dfa729ebe4f55/ 
404 in ovrstat - https://ovrstat.com/stats/nintendo-switch/LSB-82d57a445ee3315fe83dfa729ebe4f55

**Public profile user**
Exists - https://playoverwatch.com/en-us/career/nintendo-switch/HELLO-de16d87f9503bc6fa044f5f17129195e/
404 in ovrstat - https://ovrstat.com/stats/nintendo-switch/HELLO-de16d87f9503bc6fa044f5f17129195e

As far as I can tell every switch player gets 404 in ovrstat

**Comment by tystuyfzand** [comment] 2021-01-02 20:30
I noticed this too, the issue is that the API endpoint we use for searching players/getting prestige/etc does not support the name format for Nintendo Switch lookups. I have no idea how to fix this, but I'll be looking into it.

**Comment by s32x** [comment] 2021-04-11 21:56
Looks like this should be fixed now thanks to @tystuyfzand

**Closed by s32x** 2021-04-11 21:56 UTC
